# Generated by Django 4.0.3 on 2022-04-24 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=256, verbose_name='Размер')),
                ('devision', models.IntegerField(default=8, verbose_name='Делитель')),
            ],
            options={
                'verbose_name': 'Настройка отдельных параметров шифрования',
                'verbose_name_plural': 'Настройки отдельных параметров шифрования',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='masterpassword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CryptoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations', models.IntegerField(default=10, verbose_name='Кол-во интераций')),
                ('iv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_IV', to='core.cryptoparam', verbose_name='IV')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_KEY', to='core.cryptoparam', verbose_name='Ключ')),
                ('salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_SALT', to='core.cryptoparam', verbose_name='Соль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка шифрования пользователя',
                'verbose_name_plural': 'Настройки шифрования пользователей',
            },
        ),
    ]
