# Generated by Django 4.0.3 on 2022-04-24 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('system', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('browser', models.CharField(max_length=255, verbose_name='Браузер')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входа в систему',
                'verbose_name_plural': 'Истории входа в систему',
            },
        ),
    ]
