# Generated by Django 4.2.7 on 2026-03-17 13:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetting",
            options={
                "ordering": ["name"],
                "verbose_name": "Настройка сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание назначения настройки",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Имя настройки",
                max_length=255,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="value",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Значение настройки в JSON формате",
                verbose_name="Значение",
            ),
        ),
    ]
