# Generated by Django 4.0.3 on 2022-04-24 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=256, verbose_name='Размер')),
                ('devision', models.IntegerField(default=8, verbose_name='Делитель')),
            ],
            options={
                'verbose_name': 'Настройка отдельных параметров шифрования',
                'verbose_name_plural': 'Настройки отдельных параметров шифрования',
            },
        ),
        migrations.CreateModel(
            name='MasterPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер пароль',
                'verbose_name_plural': 'Мастер пароли',
            },
        ),
        migrations.CreateModel(
            name='CryptoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations', models.IntegerField(default=10, verbose_name='Кол-во интераций')),
                ('iv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_IV', to='crypto.cryptoparam', verbose_name='IV')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_KEY', to='crypto.cryptoparam', verbose_name='Ключ')),
                ('salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS_SALT', to='crypto.cryptoparam', verbose_name='Соль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка шифрования пользователя',
                'verbose_name_plural': 'Настройки шифрования пользователей',
            },
        ),
    ]
