# Generated by Django 4.0.3 on 2023-02-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpassword',
            name='crypto_settings',
            field=models.CharField(default=1, max_length=255, verbose_name='Настройки шифрования'),
            preserve_default=False,
        ),
    ]
