# Generated by Django 6.0.3 on 2026-03-20 22:06

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('site', models.CharField(max_length=255, verbose_name='Сайт')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Конфетка',
                'verbose_name_plural': 'Конфетки',
            },
        ),
        migrations.CreateModel(
            name='MasterPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('crypto_settings', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Значение настройки в JSON формате', verbose_name='Значение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер пароль',
                'verbose_name_plural': 'Мастер пароли',
            },
        ),
    ]
