# Generated by Django 6.0.3 on 2026-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='candy',
            name='login',
            field=models.TextField(verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='candy',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='candy',
            name='site',
            field=models.TextField(verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='masterpassword',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
    ]
