# Generated by Django 6.0.3 on 2026-03-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_alter_candy_description_alter_candy_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
