# Generated by Django 4.1.6 on 2023-02-16 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Модифицировано')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('data', models.TextField(verbose_name='Данные платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
